### PR TITLE
[WIP] [Issue 18] Remove Gridstack.destroy() workaround

### LINKED ISSUE #18: Gridstack: don't move/destroy DOM nodes in add_widget() & destroy()
https://github.com/troolee/gridstack.js/issues/238
https://github.com/troolee/gridstack.js/issues/216

Currently, Gridstack allows us to pass an option to `remove_widget()` so that the DOM node isn't removed from the container, but `add_widget()` and `destroy()` don't have those options.

In the meantime, we have created our own "subclass" of Gridstack which adds these options ([code](https://github.com/troolee/gridstack.js/issues/238)).

### PR DESCRIPTION
**Pull request by jhpedemonte**
Update Gridstack to 0.2.5-dev commit.

Fixes #18

### CODE REVIEW

**Comment by jhpedemonte** [comment]
This removes our GridstackCustom class, including the `destroy` workaround.

Unfortunately, there are some functional issues now (probably from updating Gridstack instance):

1. When removing cells from dashboard, the hidden cells area isn't set correctly and dashboard cells overlap hidden cells area. Seen when removing differently-tall cells on same row in **test_layout_basic**.
2. Resize handles in lower corners are drawn incorrectly now.

**Comment by parente** [comment]
I think we should stick with the workarounds for the time being if it's going to cost us new regressions. I'd rather jump wholesale and address everything at once later.

What do you think?

**Comment by jhpedemonte** [comment]
Right, this was to see if there were any issues when moving up Gridstack. Luckily one of the devs has been very responsive to issues I've found.

I'll mark this as WIP and continue with the Gridstack dev.

**Comment by parente** [comment]
:+1:

**Comment by parente** [comment]
See update in #18. Can pull this from the history of closed PRs in the future if needed.

**Pull request closed without merging**
